<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
    <title>Game</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css">
    <style>
	    * {
		margin:0;
		padding:0;
		box-sizing:border-box;
		}
		
		.console {
			height: 100vh;
			display: flex;
			flex-direction: column;
			align-items: start;
			justify-content: end;
			
			background-color: red;
		}
		
		.input-area {
			height: 10%;
			background-color: green;
		}
		
		.history-box {
			height: 90%;
			background-color: blue;
			
			overflow:auto;
			scrollbar-width: none;
			-ms-overflow-style: none;
		}
    </style>
</head>
<body>
	<div class="console">
	    <div class="history-box">
	        <c:forEach items="${gameHistory}" var="entry">
	            <div class="history-item">${entry}</div>
	        </c:forEach>
	    </div>
	
	    <form action="${pageContext.request.contextPath}/game" method="post" class="input-area">
	        <input type="text" name="userInput" placeholder="Enter your input...">
	        <button type="submit">Submit</button>
	    </form>
	</div>
	
	//Code generated by ChatGPT to auto-scroll to the bottom
	<script>
		window.addEventListener('load', () => {
	        const historyBox = document.querySelector('.history-box');
	        historyBox.scrollTop = historyBox.scrollHeight;
	    });
	</script>
</body>
</html>